### ISSUE TITLE
Fission Function Pods are getting recreated.

### ISSUE THREAD

**Issue by fauzankhan007** [fission/fission#1950] opened 2021-03-15 10:42 UTC
Fission version - 1.11.2
kubernetes version - v1.16.1
docker version : 1.13.1

Platform: Kubeadm on Redhat 7.8 server(Datacenter Server)

Issue: All Fission function pods are getting recreated(not restarted) at the same time, the age of the pods changes when gets recreated. We are not able to find the cause of this behavior, Though we find the below logs in journalctl.

```
Mar 12 01:44:47 dcacmj dockerd-current[22700]: {"level":"fatal","ts":"2021-03-12T06:44:47.055Z","logger":"builder_manager.environment_watcher","caller":"buildermgr/envwatcher.go:159","msg":"error watching environment list","error":"the server is currently unable to handle the request (get environments.fission.io)"}
Mar 12 01:44:49 dcacmj dockerd-current[22700]: E0312 06:44:49.033396       1 customresource_handler.go:649] error building openapi models for functions.fission.io: ERROR $root.definitions.io.fission.v1.Function.properties.spec.properties.configmaps has invalid property: nullable
Mar 12 01:44:57 dcacmj dockerd-current[22700]: {"level":"info","ts":"2021-03-12T06:44:57.065Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:390","msg":"Poolmanager starts to clean orphaned resources","instanceID":"ufvfutan"}
Mar 12 01:44:57 dcacmj dockerd-current[22700]: {"level":"info","ts":"2021-03-12T06:44:57.065Z","logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:285","msg":"Newdeploy starts to clean orphaned resources","instanceID":"ufvfutan"}
Mar 12 01:44:57 dcacmj dockerd-current[22700]: {"level":"info","ts":"2021-03-12T06:44:57.502Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:149","msg":"deployment created","environment":{"name":"anomaly-detection","namespace":"fission-function","selfLink":"/apis/fission.io/v1/namespaces/fission-function/environments/anomaly-detection","uid":"f23010bd-1d9a-42d7-939a-33f8daa15a8e","resourceVersion":"1858664","generation":1,"creationTimestamp":"2021-03-03T05:37:11Z","annotations":{"fission-name":"anomaly-detection-env-base","fission-uid":"d27ea856-bb13-400d-8747-d50a47dc594a"}}}
Mar 12 01:44:57 dcacmj dockerd-current[22700]: {"level":"info","ts":"2021-03-12T06:44:57.502Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:108","msg":"creating pool","environment":{"name":"monitoring-core","namespace":"fission-function","selfLink":"/apis/fission.io/v1/namespaces/fission-function/environments/monitoring-core","uid":"b1e407cd-4f46-4f40-9e52-df3ab7f6604d","resourceVersion":"2897015","generation":1,"creationTimestamp":"2021-03-10T07:24:58Z","annotations":{"fission-name":"monitoring-core","fission-uid":"2c4091dd-8f52-4e12-a530-2550cae0dfbd"}}}
```

After the above logs, we see the logs that pods are getting recreated.

```
Mar 12 01:45:22 dcacmj dockerd-current[22700]: I0312 06:45:22.609545       1 event.go:255] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"fission-function", Name:"newdeploy-alerts-consumer-fission-function-9f04-a88930f92ef3-5b69d8b99b", UID:"ef3d36ab-9fac-4047-822b-c3e22387e67c", APIVersion:"apps/v1", ResourceVersion:"3185734", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: newdeploy-alerts-consumer-fission-function-9f04-a88930f92eshjmf
```

Also below status code found in Prometheus.

```
fission_function_calls_total{application="fission-router",cached="false",code="499",controller_revision_hash="549644db6d",instance="10.244.0.190:8080",job="kubernetes-pods",kubernetes_namespace="fission",kubernetes_pod_name="router-rhrhp",method="GET",name="metadata-init",namespace="fission-function",pod_template_generation="1",svc="router"}               5
fission_function_calls_total{application="fission-router",cached="false",code="499",controller_revision_hash="549644db6d",instance="10.244.0.190:8080",job="kubernetes-pods",kubernetes_namespace="fission",kubernetes_pod_name="router-rhrhp",method="GET",name="metadata-reload",namespace="fission-function",pod_template_generation="1",svc="router"}         1
fission_function_calls_total{application="fission-router",cached="false",code="499",controller_revision_hash="549644db6d",instance="10.244.0.190:8080",job="kubernetes-pods",kubernetes_namespace="fission",kubernetes_pod_name="router-rhrhp",method="POST",name="metric-processing",namespace="fission-function",pod_template_generation="1",svc="router"} 26
```

How to reproduce this issue? 
We don't know what is happening exactly, and how we can recreate this scenario!!

Attached the fission-dump, Also shared the journalctl logs.
[fission-dump.zip](https://github.com/fission/fission/files/6140519/fission-dump.zip)

**Comment by hd40910** [comment] 2021-03-15 10:57
@vishal-biyani  Can you please us with this ?

**Comment by vishal-biyani** [comment] 2021-03-22 09:42
This looks more like an issue with K8S master not being reachable. Because of which Fission can not get env list and then fails:

```
the server is currently unable to handle the request (get environments.fission.io)"}
```

Same can be said from fission dump logs. Do you know if K8S master setup is stable and responding to other calls?

**Comment by fauzankhan007** [comment] 2021-03-22 09:52
Yes other pods were responsive at that time. 
Also fission-function pods were responsive just before the recreation of the pods.

**Comment by vishal-biyani** [comment] 2021-03-22 09:59
@fauzankhan007 Is there a way to reproduce this clearly or do you any event when this happens?

**Comment by fauzankhan007** [comment] 2021-03-22 10:47
Unfortunately we don't know how to reproduce the issue, this is very random sometimes this issue occurs in few hours sometimes it happens  in few days. We get similar logs for Service, Pod, Deployment, replication etc as well.
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:43.259002       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: Get https://172.23.251.205:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.23.251.205:6443: connect: connection refused`
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:43.258163       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: Get https://172.23.251.205:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp 172.23.251.205:6443: connect: connection refused`
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:43.261253       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: Get https://172.23.251.205:6443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 172.23.251.205:6443: connect: connection refused`
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:43.262356       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: Get https://172.23.251.205:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0: dial tcp 172.23.251.205:6443: connect: connection refused`
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:25.872226       1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.Deployment: Get https://10.96.0.1:443/apis/extensions/v1beta1/deployments?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused`
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:25.873327       1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1.Job: Get https://10.96.0.1:443/apis/batch/v1/jobs?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused`
`Mar 12 01:43:49 dcacmj dockerd-current[22700]: E0312 06:43:25.875445       1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v2beta1.HorizontalPodAutoscaler: Get https://10.96.0.1:443/apis/autoscaling/v2beta1/horizontalpodautoscalers?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused`

Above logs won't cause any issue to the pods and cluster is reachable, but when we get below logs
`Mar 12 01:44:47 dcacmj dockerd-current[22700]: {"level":"fatal","ts":"2021-03-12T06:44:47.055Z","logger":"builder_manager.environment_watcher","caller":"buildermgr/envwatcher.go:159","msg":"error watching environment list","error":"the server is currently unable to handle the request (get environments.fission.io)"}
`
K8s recreates all the fission-function pods.

**Comment by vishal-biyani** [comment] 2021-03-25 16:48
Hi, @fauzankhan007 I don't think this is a problem only with Fission, as you can see from other errors of for ex. Kafka running inside K8S cluster with Strimzi operator:

```
Mar 12 01:44:38 dcacmj dockerd-current[22700]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

```
Mar 12 01:44:38 dcacmj dockerd-current[22700]: [2021-03-12 06:44:37,195] ERROR <opicOperator:1275> [oop-thread-0] 1108867|periodic kafka api_content: Error getting KafkaTopic api-content---88d99f0d44ab207fe1dd6f2344fecb35472a830a for topic api_content
```

Secondly, are you running this on a single node cluster? That is really not the supported configuration. If you are running on a single node - master and all worker workloads such as Kafka, Fission, Functions, and whatnot, it is really tough to diagnose underlying problems unless we access the system.

I will close this issue here - because of unsupported configuration and this not being a Fission specific problem really!

**Closed by vishal-biyani** 2021-03-25 16:48 UTC
