### ISSUE TITLE
Exception when deploying java function

### ISSUE THREAD

**Issue by yair12** [fission/fission#1641] opened 2020-06-09 18:07 UTC
https://github.com/fission/fission/blob/65fd1d9fbb6a16ecce1bdb31e3056ffa56317191/environments/jvm/src/main/java/io/fission/Server.java#L60

Hi,

Using: fission-all-1.9.0-minikube

I am getting FileNotFoundException when specialize is called.

INFO 1 --- [nio-8888-exec-3] global                                   : Entrypoint class:io.fission.HelloWorld
java.io.FileNotFoundException: /userfunc/deployarchive (Is a directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at io.fission.Server.specialize(Server.java:60)

I followed the example provided for java and instructions here:
https://docs.fission.io/docs/languages/java/

Please advise.

Thanks!

**Comment by yair12** [comment] 2020-06-09 18:33
When renaming the pod local archive inside /userfunc/deployarchive to deployarchive the function is deployed successfully. 
I assume either the caller to specialize should send the full path to the file, or the implementation should look inside deployarchive directory.

**Comment by vishal-biyani** [comment] 2020-06-10 03:25
Hi @yair12 This is a duplicate of this one: https://github.com/fission/fission/issues/1636#issuecomment-640657902

**Closed by vishal-biyani** 2020-06-10 03:25 UTC
