### ISSUE TITLE
getting error while running a function

### ISSUE THREAD

**Issue by meysam001** [fission/fission#631] opened 2018-04-17 05:57 UTC
Hello
When I run a function, I will get the error message like this:
```
fission fn list
NAME  UID                                  ENV    EXECUTORTYPE MINSCALE MAXSCALE TARGETCPU
hello 6a0159b0-4202-11e8-9901-ce0dcdd7b986 nodejs poolmgr

#fission function test --name hello
Failed to execute HTTP request: Get http://[my ip]:31314/fission-function/hello: dial tcp [my ip]:31314: getsockopt: connection refused
```

fission version: 
```
Client Version: {"GitCommit":"0247ea488e7e2f4b23b46ec9757d7b381caccf81","BuildDate":"2018-04-02T22:54:21Z","Version":"0.7.0"}
Server Version: {"GitCommit":"0247ea488e7e2f4b23b46ec9757d7b381caccf81","BuildDate":"2018-04-02T22:54:21Z","Version":"0.7.0"}
```
helm version: 
```
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```
OS: `Linux srv 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux`

**Comment by pl04351820** [comment] 2018-04-17 16:29
Hi @meysam001 
Can you check the fission router port number by running
```
$ kubectl -n fission get svc router -o jsonpath='{...nodePort}'
```

**Comment by meysam001** [comment] 2018-04-18 05:11
I ran it, It returned nothing.

**Comment by life1347** [comment] 2018-04-18 17:46
Hi @meysam001 
From the log attached, I guess the current value of environment varaible `FISSION_ROUTER` is =`[my ip]:31314`. Could you check what's value of environment variable? 
If it's not empty, please try to use `unset` to unset the environment variable and try again.
```
unset FISSION_ROUTER
```
If it not works, could you please paste the output of following commands? Thanks!
```
$ kubectl -n fission get svc
$ kubectl -n fission get svc router -o yaml
```

**Comment by meysam001** [comment] 2018-04-21 05:27
Hi @life1347 
The value of env variable `FISSION_ROUTER ` was `:31314` and I replaced it with `178.162.203.172:3134`.
Then I removed all env,routes and functions that recreated and ran them again:
```
fission env create --name nodejs --image fission/node-env
fission function create --name hello --env nodejs --code hello.js
fission route create --method GET --url /hello --function hello
curl http://$FISSION_ROUTER/hello
#output is: curl: (7) Failed to connect to 178.162.203.172 port 31314: Connection refused
```

The output of `kubectl -n fission get svc` is:
```
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
controller       NodePort       10.106.88.176    <none>        80:31313/TCP     3d
executor         ClusterIP      10.106.69.156    <none>        80/TCP           3d
influxdb         ClusterIP      10.104.157.52    <none>        8086/TCP         3d
nats-streaming   NodePort       10.102.164.64    <none>        4222:31316/TCP   3d
router           LoadBalancer   10.111.192.178   <pending>     80:32672/TCP     3d
storagesvc       ClusterIP      10.106.48.97     <none>        80/TCP           3d
```

The output of `kubectl -n fission get svc router -o yaml` is:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-04-17T05:42:51Z
  labels:
    application: fission-router
    chart: fission-all-0.7.0
    svc: router
  name: router
  namespace: fission
  resourceVersion: "976491"
  selfLink: /api/v1/namespaces/fission/services/router
  uid: 2b18f0c7-4202-11e8-9901-ce0dcdd7b986
spec:
  clusterIP: 10.111.192.178
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32672
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    svc: router
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by life1347** [comment] 2018-04-24 07:29
Hi @meysam001 , sorry for the late reply.
Is `178.162.203.172` is IP address of k8s cluster node?
If yes, from the output of `kubectl -n fission get svc`
```
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
router           LoadBalancer   10.111.192.178   <pending>     80:32672/TCP     3d
```
The correct value for `FISSION_ROUTER` should be like
```
<node ip>:<svc nodeport>
178.162.203.172:32672
```

**Comment by white-cloud** [comment] 2018-04-24 07:39
Hello @life1347 , 

Please i'm facing the same problem to access my function from another node out of the cluster , and the problem is in the router setting !.

**Comment by meysam001** [comment] 2018-04-24 08:32
@life1347 
Yes, the `178.162.203.172` is the IP address of k8s cluster node (master node).
```
#kubectl -n fission get svc
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
controller       NodePort       10.106.88.176    <none>        80:31313/TCP     7d
executor         ClusterIP      10.106.69.156    <none>        80/TCP           7d
influxdb         ClusterIP      10.104.157.52    <none>        8086/TCP         7d
nats-streaming   NodePort       10.102.164.64    <none>        4222:31316/TCP   7d
router           LoadBalancer   10.111.192.178   <pending>     80:32672/TCP     7d
storagesvc       ClusterIP      10.106.48.97     <none>        80/TCP           7d
```

I think, I saw that the `FISSION_ROUTER ` was in the document like this:
```
export FISSION_URL=http://$(minikube ip):31313
export FISSION_ROUTER=$(minikube ip):31314
```
Anyway, when I changed `FISSION_ROUTER ` to `178.162.203.172:32672`, It works!
```
fission function test --name hello
#Hello, world!
```

1. It seems that the port was changed in new version. Is it true?
2. Is it necessary to set `FISSION_URL` ? 

Thanks

**Comment by life1347** [comment] 2018-04-24 09:01
Good to hear it works now! 
Sorry for the confusion. I will update a section to explain how to set `FISSION_ROUTER` properly.

And for questions:

1. If fission is install with helm variable `routerServiceType=NodePort `, then port will be 31314. Otherwise, k8s will assign a port for router service. So, I will recommend following way to get router port
```
$ kubectl -n fission get svc router -o jsonpath='{...nodePort}'
32471
```

2: No, it's not necessary to set `FISSION_URL` from 0.6.0. The CLI will try to get controller service information automatically.

**Comment by life1347** [comment] 2018-04-24 09:12
Hi @white-cloud !

The function should be able to access from another node out of cluster with the following function url
```
# routerServiceType = LoadBalancer
http://$(kubectl -n <fission namespace> get svc router -o jsonpath='{...ip}')/<trigger path>

# routerServiceType = NodePort
http://<node ip>/$(kubectl -n fission get svc router -o jsonpath='{...nodePort}')/<trigger path>
```
If it's still not work, would you mind to paste the output of `kubectl -n fission get svc` ?

**Comment by white-cloud** [comment] 2018-04-24 09:27
Hello @life1347 

Thank you for your answer.
So i put there the node Ip of the master node not the worker node ?
this configuration of the fission router i do it manually each time i wanna call tje function from outside the cluster ? as i'm using  **routerServiceType = NodePort**

**Comment by life1347** [comment] 2018-04-24 09:41
@white-cloud , could you try worker node IP instead? If I remember correctly, the node (master) without `kubelet` is not able to forward traffic between cluster minion nodes.

**Comment by white-cloud** [comment] 2018-04-24 10:01
Actually i tried them both with the same of course with the same Nodeport of the router service and it worked i could call the function , but what i'm wondering now that is that okay to call that function with that way without configuring the env variable (router, fission Url)?

**Comment by meysam001** [comment] 2018-04-24 10:35
Thank you @life1347 for helping :+1:

**Comment by chinmay5** [comment] 2018-04-24 17:27
IMHO  in the [installation documentation for Minikube](https://docs.fission.io/0.7.0/installation/installation/#minikube), we should pass `--set routerServiceType=NodePort`. If it's ok for you I can open a pull request

**Comment by life1347** [comment] 2018-04-25 14:32
@white-cloud 
For `FISSION_URL`, from 0.6. it's no need to set it as long as the node has local kubeconfig to the cluster. Otherwise, you still set it since fission CLI need a way to know where the fission API server is.

For `FISSION_ROUTER`
Unfortunately, it's necessary to set `FISSION_ROUTER` for now if you want to access the HTTP trigger of function. If the IP address of worker node is always changed, I think you can set up an [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) to forward traffic to the router, in this way you can set ingress IP as env value (need to be accessible from outside of cluster).

**Comment by life1347** [comment] 2018-04-25 14:33
@chinmay5 sure, it's definitely welcome.

**Comment by vishal-biyani** [comment] 2018-05-14 10:08
Closing this for now as queries have been resolved above. If you have issues still, please raise a new issue.

**Closed by vishal-biyani** 2018-05-14 10:08 UTC
