### ISSUE TITLE
Executor unable to respond to router under massive traffic

### ISSUE THREAD

**Issue by life1347** [fission/fission#1863] opened 2020-11-20 10:22 UTC
In PR https://github.com/fission/fission/commit/f3fe3123b3130afdc661cdde648d04e5efae70df , router no longer checks it's own cache before talking to executor which become a problem if router is under heavy workload.

It's dangerous for router to send a request for asking function service url whenever it receives a request from client. Router should have a mechanism that somehow able to reduce the requests to executor. 

# How to reproduce

1. Create two hello-world functions with executor type `newdeploy`. `hw1` & `hw2`
2. Call to hw2 with `ab -n 500000 -c 200 http://<router-ip>/hw2`
3. Before `ab` is finished, call `hw1`
4. The call to `hw1` failed and router prints logs

```
router-598c9f685d-2s6bg router 2020-11-20T01:13:33.887Z	ERROR	triggerset.http_trigger_set.tr	
router/functionHandler.go:535	error from GetServiceForFunction	{"error": "error posting to getting 
service for function: context deadline exceeded", "errorVerbose": "context deadline exceeded\nerror 
posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.
(*Client).GetServiceForFunction\n\t/go/src/pkg/executor/client/client.go:78\ngithub.com/fission/fission
/pkg/router.functionHandler.getServiceEntryFromExecutor\n\t/go/src/pkg/router/functionHandler.go:532\ng
ithub.com/fission/fission/pkg/router.
(*RetryingRoundTripper).RoundTrip\n\t/go/src/pkg/router/functionHandler.go:187\nnet/http/httputil.
(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:259\ngithub.com/fissio
n/fission/pkg/router.functionHandler.handler\n\t/go/src/pkg/router/functionHandler.go:424\nnet/http.Han
dlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.
(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission
/pkg/router.
(*mutableRouter).ServeHTTP\n\t/go/src/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.
(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serve
rHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.
(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime
/asm_amd64.s:1337", "error_message": "error posting to getting service for function: context deadline 
exceeded", "function": {"kind":"Function","apiVersion":"fission.io/v1","metadata":
{"name":"tracker2","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/t
racker2","uid":"8e7f614b-896c-4696-b872-
88518fb955b8","resourceVersion":"1001184","generation":1,"creationTimestamp":"2020-11-
20T00:48:52Z","managedFields":[{"manager":"fission-
bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-11-20T00:48:52Z"}]},"spec":
{"environment":{"namespace":"default","name":"nodebeta4"},"package":{"packageref":
{"namespace":"default","name":"tracker2-713cdf6f-4fa6-425a-a6b4-
e53d4dc0144a","resourceversion":"1001179"}},"secrets":null,"configmaps":
[{"namespace":"default","name":"fissionfunction-tracker2"}],"resources":{"limits":
{"cpu":"100m"},"requests":{"cpu":"1m"}},"InvokeStrategy":{"ExecutionStrategy":
{"ExecutorType":"newdeploy","MinScale":3,"MaxScale":12,"TargetCPUPercent":50,"SpecializationTimeout":20
0},"StrategyType":"execution"},"functionTimeout":5,"idletimeout":120,"concurrency":200}}, 
"status_code": 500}
```

**Comment by therahulbhati** [comment] 2020-11-27 14:24
@life1347 For better performance, we have moved the cache to the executor and made the router stateless. Can you try to increase client-side timeout and replicas of the router?

**Comment by jingb** [comment] 2021-03-05 02:21
@therahulbhati I have also meet this question
when router receive a request, it will send a req to executor to get funtion address, and executor will send a req to k8s apiserver to get function's detail. In a poolmgr type env, when get a pod from cache, it will send a req to k8s apiserver to get the pod's detail. And validate its status then send back to router. In another word, the function request link depends on k8s apiserver and executor, have a plan to reduce this process ?

**Comment by therahulbhati** [comment] 2021-03-05 06:22
Hi @jingb, I have addressed this in https://github.com/fission/fission/pull/1919, this would eliminate an API call to k8s apiserver.

**Comment by jingb** [comment] 2021-03-08 08:11
hi @therahulbhati   how about the method  (executor *Executor) getServiceForFunction(fn *fv1.Function)
I see some comment on this method that it plan to make a optimization.
Eliminate the api call to k8s apiserver during the pod validation process for poolMgr mode.

**Comment by info2000** [comment] 2021-05-10 18:54
> @life1347 For better performance, we have moved the cache to the executor and made the router stateless. Can you try to increase the client-side timeout to a big value and replicas of the router?

with fission v 1.11.2 3 router replicas: works awesome
with fission v 1.12, 6 router replicas, fission doesn't respond
with 427 request per minute, and 6 nodes

**Comment by vishal-biyani** [comment] 2021-05-12 06:56
Hey @info2000 and @life1347 - point noted. Will test this update here. 
The cache move was for reasons that seemed right in larger perspective but of course there is a trade off. We will have to re-design that soon for sure.

**Comment by smartm13** [comment] 2021-07-01 10:15
Hi @vishal-biyani,
I am facing the similar issue: Getting lot of 500 status codes reported only on higher loads. Stack-Trace being:
```
context deadline exceeded
error posting to getting service for function
github.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction
        /go/src/pkg/executor/client/client.go:83
github.com/fission/fission/pkg/router.functionHandler.getServiceEntryFromExecutor
        /go/src/pkg/router/functionHandler.go:531
github.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip
        /go/src/pkg/router/functionHandler.go:189
net/http/httputil.(*ReverseProxy).ServeHTTP
        /usr/local/go/src/net/http/httputil/reverseproxy.go:259
github.com/fission/fission/pkg/router.functionHandler.handler
        /go/src/pkg/router/functionHandler.go:424
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:1995
github.com/gorilla/mux.(*Router).ServeHTTP
        /go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212
github.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP
        /go/src/pkg/router/mutablemux.go:52
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
        /go/pkg/mod/go.opencensus.io@v0.22.4/plugin/ochttp/server.go:92
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2774
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1878
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```
Does the newer release v1.13.1 fix this?

**Comment by vishal-biyani** [comment] 2021-07-01 10:52
Hey @smartm13 Can you please tell us a bit more about your workload - how much and how you increased it etc. Also if you can share fission dump when this happens, it will be useful!

**Comment by smartm13** [comment] 2021-07-01 11:43
I have a setup of mqt-kafka triggering **4 fission-functions** from their corresponding kafka topics.
All 4 functions are of newdeploy type and have fixed number of pods: **10, 8, 6, 1**
The rate of msgs being streamed to kafka topics are like **1000, 200, 0.125, 4 messages pushed per second** respectively.
This is being done on single-node k8s cluster with 32GB ram and 8 core machine. (Both CPU and Memory were way below the limits all the times)

I have tried to get the fission dump now, while the issue was seen from **2021-06-29T13:00 UTC** to **2021-06-30T09:20 UTC** and now we dont have that high load running. Hope the logs have it covered. (Shared the dump over email)

**Comment by sanketsudake** [comment] 2021-07-28 06:29
Just to summarize recent changes which are available  >1.13.1

1. Router cache is added back for new deploy functions via https://github.com/fission/fission/commit/377600d0a3428470c4356b5d3b58e6b0fb68a2a5 . 
2. Additional to this https://github.com/fission/fission/pull/1919 which Rahul mentioned, we have also reduced K8s API calls by adding informers for Pod https://github.com/fission/fission/commit/4038f0384b4f0962496aed8046ea038563a5c7be

**Comment by sanketsudake** [comment] 2021-07-28 15:09
I tried the scenario mentioned in the issue description, with the latest code(upcoming 1.14 release).

#### Setup

Create a kind cluter locally and two fission functions with newdeploy.
```bash
fission env create --name nenv1 --image fission/node-env --poolsize 1
fission env update --name nenv1 --poolsize 0
fission env create --name nenv2 --image fission/node-env --poolsize 1
fission env update --name nenv2 --poolsize 0
fission fn create --name hw1 --env nenv1 --code examples/nodejs/hello.js --executortype newdeploy
fission fn create --name hw2 --env nenv2 --code examples/nodejs/hello.js --executortype newdeploy
fission route create --name hw1 --function hw1 --url /hw1
fission route create --name hw2 --function hw2 --url /hw2
```

#### Running load

```bash
$ ab -n 500000 -c 200 http://localhost:8888/hw2
Finished 500000 requests
Concurrency Level:      200
Time taken for tests:   2667.757 seconds
Complete requests:      500000
Failed requests:        0
Total transferred:      97000000 bytes
HTML transferred:       7000000 bytes
Requests per second:    187.42 [#/sec] (mean)
Time per request:       1067.103 [ms] (mean)
Time per request:       5.336 [ms] (mean, across all concurrent requests)
Transfer rate:          35.51 [Kbytes/sec] received
```
In meantime I made requests hw1 also concurrently, requests were getting processed successfully. 
I did small workloads as,
```bash
$ ab -n 100  -c 10  http://localhost:8888/hw1
Concurrency Level:      10
Time taken for tests:   10.739 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      19400 bytes
HTML transferred:       1400 bytes
Requests per second:    9.31 [#/sec] (mean)
Time per request:       1073.850 [ms] (mean)
Time per request:       107.385 [ms] (mean, across all concurrent requests)
Transfer rate:          1.76 [Kbytes/sec] received
```

So we can assume bottlenecks for new deploy seems a lot lower. 

This analysis may not apply for pool-manager as for pool-manager we will still reach out to the executor for each request & we don't utilize router cache.

**Comment by info2000** [comment] 2021-08-17 15:51
@vishal-biyani there's some update about this issue? do you want access to a cluster with continous traffic having this issue?

**Comment by info2000** [comment] 2021-09-20 00:12
I upgrade from 1.10 to 1.14.1 and increased the issues with
"context cancelled" to the function with most traffic
and  "unable to get service url for connection" and "serviceURL is empty for function" to functions with less traffic

**Comment by sanketsudake** [comment] 2022-01-17 05:11
So as per above comments,

1. We have added router cache for newdeploy pods again.
2. Where as for pool manage based pods we can really think of adding router cache back as we need to support for better control mechanism.

Typically issues seen on via debugging are mostly due to inappropriate pool size or specialization taking time out so users function call not getting specialized URL due to that.

Also as [posted above](https://github.com/fission/fission/issues/1863#issuecomment-888389545) reproduction didn't happen for newdeploy.

I think we can close this issue with the evidences and debugging done so far. Feel free to reopen issue if any specifics.

Future enhancements we may consider for better solution:
1. Consider moving router to executer communication to Grpc
2. Scalability for executor

**Closed by sanketsudake** 2022-01-17 05:11 UTC
Labels: bug, area-performance, area-executor
