### ISSUE TITLE
Fission fn of type newdeploy fails to specialize with timeout - Version 1.5

### ISSUE THREAD

**Issue by hd40910** [fission/fission#1408] opened 2019-11-15 15:05 UTC
$ fission fn list | grep mapper
mapper                                26c323cb-07b4-11ea-af6d-005056af10ec atomiq-py-core     newdeploy    1        3        0      0      0         0         80

**ERROR  LOGS:**
sudo journalctl -n 10000000 --no-pager | grep mapper

Nov 15 16:30:11 ilgss??? dockerd-current[40737]: {"level":"error","ts":1573828211.84828,"logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:289","msg":"error creating k8s resources for function","error":"error creating deployment newdeploy-mapper-default-vu4uvtnr: **failed to create deployment within the timeout window of 120** seconds","errorVerbose":"failed to create deployment within the timeout window of 120 seconds\nerror creating deployment newdeploy-mapper-default-vu4uvtnr\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).fnCreate\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:358\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).createFunction.func1\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:282\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\t/go/src/pkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).createFunction\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:280\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).initFuncController.func1.1\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:146\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","function_name":"mapper","function_namespace":"default"}
Nov 15 16:30:11 ilgss??? dockerd-current[40737]: {"level":"error","ts":1573828211.8483536,"logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:148","msg":"error eager creating function","error":"error creating k8s resources for function mapper_default: error creating deployment newdeploy-mapper-default-vu4uvtnr: failed to create deployment within the timeout window of 120 seconds","errorVerbose":"**failed to create deployment within the timeout window of 120 seconds**\nerror creating deployment newdeploy-mapper-default-vu4uvtnr\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).fnCreate\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:358\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).createFunction.func1\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:282\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\t/go/src/pkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).createFunction\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:280\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).initFuncController.func1.1\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:146\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nerror creating k8s resources for function mapper_default\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).createFunction\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:293\ngithub.com/fission/fission/pkg/executor/newdeploy.(*NewDeploy).initFuncController.func1.1\n\t/go/src/pkg/executor/newdeploy/newdeploymgr.go:146\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","function":"&TypeMeta{Kind:,APIVersion:,}"}
Nov 15 16:30:12 ilgss0??? dockerd-current[40737]: 2019-11-15 14:30:12.011349 W | etcdserver: read-only range request "key:\"/registry/horizontalpodautoscalers/fission-function/newdeploy-mapper-default-vu4uvtnr\" " with result **"range_response_count:0 size:5" took too long (111.823822ms) to execute**
Nov 15 16:36:15 ilgss0??? kubelet[38460]: E1115 16:36:15.675060   38460 kubelet_pods.go:1086] Failed killing the pod "newdeploy-mapper-default-vu4uvtnr-6dbbb9bbd4-nkg4p": failed to "KillContainer" for "mapper" with KillContainerError: "rpc error: code = Unknown desc = Error: No such container: 612b8c04001cc14fe486610b916f7c2ac3daef305d9235608f17e20ba83c6b06"

**Spec  :** 
```
include:
- '*.py'
kind: ArchiveUploadSpec
name: default-sSuv

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: cos
  namespace: TOKEN_NAMESPACE
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://default-sSuv
  environment:
    name: atomiq-py-core
    namespace: TOKEN_ENV_NAMESPACE
  source:
    checksum: {}
status:
  buildstatus: none

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: mapper
  namespace: TOKEN_NAMESPACE
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps:
  - name: mapper-config
    namespace: TOKEN_NAMESPACE
  - name: account-configmap
    namespace: TOKEN_NAMESPACE
  environment:
    name: atomiq-py-core
    namespace: TOKEN_ENV_NAMESPACE
  package:
    functionName: mapper.main
    packageref:
      name: cos
      namespace: TOKEN_NAMESPACE
  resources: {}
  secrets: null
```

**Comment by hd40910** [comment] 2019-11-15 15:08
@viveksinghggits can you help ?

**Comment by viveksinghggits** [comment] 2019-11-15 16:21
Hi @hd40910 
can you please mentioned the when are you getting these errors and how can we reproduce them. Assume that noone knows about the context you are talking about.

**Comment by hd40910** [comment] 2019-11-15 19:20
Hi @viveksinghggits ,

After deploying a function with "ExecutorType: newdeploy", when fission tires to create k8s resources for function. It fails with the given error above.

Looks like there is a new feature of default timeout from version 1.5.
Another thing is that once it fails, it does not try to redeploy the function once again.

Question is : What can be done to fix the timeout ?
Another Question is : is there any new limitation which is cause it not to be redeployed ?

**Comment by viveksinghggits** [comment] 2019-11-16 05:17
Hi @hd40910 ,
for the timeout issue you can see that this PR was merged 
https://github.com/fission/fission/pull/1284
in version 1.6.
so I think, you should not have function level timeout code if you are using version 1.5 and lets say that we have timeout implemented in httptriggers, what is the problem that you are facing because of that. 


> After deploying a function with "ExecutorType: newdeploy", when fission tires to create k8s resources for function. It fails with the given error above.
I dont think above issue has something to do with the default timeout.
> Looks like there is a new feature of default timeout from version 1.5.
> Another thing is that once it fails, it does not try to redeploy the function once again.
Let me try to recreate, and update.

**Comment by life1347** [comment] 2019-11-16 09:17
@hd40910 could you also try with 1.6.0 since 1.5.0 has a known issue in the executor.

**Comment by hd40910** [comment] 2019-11-17 14:30
@life1347 I was able to recreate the same in 1.6.0

![image](https://user-images.githubusercontent.com/17830882/69008820-d1dd0280-0974-11ea-8f0b-f89d2765dbdd.png)


![image](https://user-images.githubusercontent.com/17830882/69008830-f507b200-0974-11ea-8d1b-6ef26d4fb560.png)

**Comment by life1347** [comment] 2019-11-17 15:17
@hd40910 you have to upgrade your CLI to 1.6.0 as well in order to set specialization timeout.

> is there any new limitation which is cause it not to be redeployed
This is the issue we are trying to address in https://github.com/fission/fission/issues/1233

Just out of curiosity, does your function works in any older version? Because the newdeploy default timeout setting is the same as we had in 1.0.0 (120seconds).

**Comment by life1347** [comment] 2019-11-18 02:07
@hd40910 could you also provide the spec file of the environment? Thanks

**Comment by msshroff** [comment] 2019-11-18 07:23
Hi @life1347  

Issue still persists post using fission client version 1.6.0
<pre>
# fission -v
client:
  fission/core:
    BuildDate: "2019-10-10T18:24:57Z"
    GitCommit: 08b6d43ac1f1fa72854438aa6db636fd04c93098
    Version: 1.6.0
server:
  fission/core:
    BuildDate: "2019-10-10T18:24:57Z"
    GitCommit: 08b6d43ac1f1fa72854438aa6db636fd04c93098
    Version: 1.6.0
</pre>


Specs for the fission function is below: 
<pre>
# cat function-atomiq-span.yaml
include:
- atomiq_span.py
kind: ArchiveUploadSpec
name: atomiq-span-py-ltbo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: atomiq-span-py-oopi
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://atomiq-span-py-ltbo
  environment:
    name: atomiq-py-ssh
    namespace: fission-function
  source:
    checksum: {}
status:
  buildstatus: none

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: atomiq-span
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 360
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: atomiq-py-ssh
    namespace: fission-function
  package:
    packageref:
      name: atomiq-span-py-oopi
      namespace: default
  resources: {}
  secrets: null
</pre>

<pre>
</pre>

**Comment by msshroff** [comment] 2019-11-19 12:12
Same issue is there in 1.6 as well.
Spec file for the fission environment looks like below:

<pre>
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: atomiq-py-core
  namespace: fission-function
spec:
  TerminationGracePeriod: 360
  builder: {}
  keeparchive: false
  poolsize: 1
  resources: {}
  runtime:
    functionendpointport: 0
    image: aaf/fission_environment/atomiq-py-core:TOOL_GIT_BRANCH_TOOL_BUILD_NUMBER
    container:
       env:
       - name: JAEGER_AGENT_HOST
         value: jaeger-agent.jaeger.svc.cluster.local
       - name: ENABLE_TRACING
         value: "true"
    loadendpointpath: ""
    loadendpointport: 0
  version: 3
</pre>

**Comment by life1347** [comment] 2019-11-20 07:02
@msshroff I notice the checksum field is empty. Could you check the fetcher log in function pod if its checksum error?
```
"msg":"failed to verify checksum","error":"Invalid argument - Unsupported checksum type"
```
for example
```
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: "2019-11-20T06:56:29Z"
  generation: 1
  name: fission-q5yx
  namespace: default
  resourceVersion: "1145613"
  selfLink: /apis/fission.io/v1/namespaces/default/packages/fission-q5yx
  uid: 4a1ccd97-a0b1-42b4-be15-4ea38141c0d0
spec:
  deployment:
    checksum:
      sum: 1b8451aec675bfcdefd4bf1f524567ff8e8cbfb978ffba230736bc4081e591f3
      type: sha256
    type: url
    url: http://storagesvc.fission/v1/archive?id=%2Ffission%2Ffission-functions%2F4ae88174-bd82-41c6-a7e8-392f0dd62ffb
  environment:
    name: node
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: succeeded
  lastUpdateTimestamp: "2019-11-20T06:56:29.192507Z"
```

This checksum problem has been addressed in 1.7.0. So you have two options:

1. Provide sha256 checksum like above.
2. Change the fetcher image in executor deployment to fission/fetcher:1.7.0-rc.1. 
```
        env:
        - name: FETCHER_IMAGE
          value: fission/fetcher:1.7.0-rc.1
```

**Comment by hd40910** [comment] 2019-11-20 17:47
@life1347 We were finally able to figure out the actual issue for this.
If you look at the spec of the function, it uses 2 config maps for execution.
Issue was that account-config map was not present in the environment.Things look fine after adding the CM.
We could figure this out after downgrading back to version 1.2.
Unlike version 1.5 and 1.6, the kubernetis logs clearly state that the pod is not able to specialize because of missing CM and goes to crash loopback state.
But in 1.5 and above the pod simply does not appear and the logs is showing timeout error.

<pre>
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps:
  - name: mapper-config
    namespace: TOKEN_NAMESPACE
  - name: account-configmap
    namespace: TOKEN_NAMESPACE
  environment:
    name: atomiq-py-core
    namespace: TOKEN_ENV_NAMESPACE
  package:
</pre>

Another question would be to understand if there can be a check to validate if required resource to specialize a pod are present ?
Do we look at this as a bug ? or was it a architectural change ?

**Comment by life1347** [comment] 2019-11-20 17:53
@hd40910 thanks for providing the update. I need to compare the 1.2 and 1.5 to see what makes the difference and will update this thread then.

**Comment by life1347** [comment] 2019-11-21 09:09
@hd40910 could you share the error log you saw, cause in 1.6.0 the fetcher still prints error log when failed to get the secret/configmap.

https://github.com/fission/fission/blob/08b6d43ac1f1fa72854438aa6db636fd04c93098/pkg/fetcher/fetcher.go#L426-L442

**Comment by vishal-biyani** [comment] 2020-05-11 16:33
Closing for lack of response.

**Closed by vishal-biyani** 2020-05-11 16:33 UTC
