### ISSUE TITLE
Fission ENV update failing with out image parameter

### ISSUE THREAD

**Issue by swaroopnuli** [fission/fission#1718] opened 2020-09-18 12:36 UTC
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2020-09-16T15:37:59Z"
    GitCommit: 09b4ffed78ad7a7eea7ebaf47e7644843b0a0b12
    Version: 1.11.0
server:
  fission/core:
    BuildDate: "2020-09-16T13:41:28Z"
    GitCommit: f034a1c734af51cdd6dd4449d1db253a67e699c3
    Version: 1.11.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
AWS EKS

**Describe the bug**
fission update env with just pool size is failing without image parameter

`fission env update --name <env-name> --poolsize 5`

**To Reproduce**

**Expected result**
ENV Poolsize simply updated

**Actual result**

`Error: 1 errors occurred:
	* need --image to specify env image, or use --builder to specify env builder, or use --buildcmd to specify new build command`

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by vishal-biyani** [comment] 2020-09-21 11:04
Similar/Duplicate of https://github.com/fission/fission/issues/1721

**Closed by vishal-biyani** 2020-09-21 11:04 UTC
