### ISSUE TITLE
Nginx Ingress with URL parameters gives 404

### ISSUE THREAD

**Issue by aberfeldy** [fission/fission#1312] opened 2019-09-11 09:36 UTC
**Fission/Kubernetes version**
Fission:
<pre>
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
</pre>
kubectl: 
<pre>
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Hetzner cloud self hosted

**Describe the bug**
If I follow the docs for exposing a function with an ingress and the function contains a restful path (e.g. `/test/{name}` the ingress will be created successfully, but the HTTP call to `http://<hostname>/test/Peter` results in a 404 of the default backend.
In the nginx ingress logs lines like that can be found:
<pre>
2019/09/11 09:14:33 [emerg] 2715#2715: unknown directive "foobar}" in /tmp/nginx-cfg570981444:660
nginx: [emerg] unknown directive "foobar}" in /tmp/nginx-cfg570981444:660
nginx: configuration file /tmp/nginx-cfg570981444 test failed
</pre>

**To Reproduce**
Follow the docs at [https://docs.fission.io/usage/ingress-tutorial/](https://docs.fission.io/usage/ingress-tutorial/) and try to print the X-Fission-Params Header from within the function.
Route was created with 
`fission httptrigger create --url "/test/{name}" --function hello --createingress --host <hostname> --name hello-ingress`
**Expected result**
That the route is matched and the X-Fission-Params are set corresponding to the path params
**Actual result**
default backend - 404 (the nginx ingress default backend)

**Additional context**
Maybe I'm missing something in the docs, are the URL params like /{whatever} even supported with an ingress or is it just working via the fission router?

**Comment by life1347** [comment] 2019-09-16 01:24
Thanks for providing the information. We've scheduled to fix this in the 1.6 milestone.
Duplicate of https://github.com/fission/fission/issues/1158 , so close this.

**Closed by life1347** 2019-09-16 01:24 UTC
