### ISSUE TITLE
Unable to update fn scale even when updating both min&maxscale 

### ISSUE THREAD

**Issue by life1347** [fission/fission#872] opened 2018-08-26 07:57 UTC
```
fission fn update --name test --executortype newdeploy --minscale 3 --maxscale 3
Minscale provided: 3 can not be greater than maxscale of existing function: 1
```

**Comment by vishal-biyani** [comment] 2018-08-27 05:05
Related/Duplicate of https://github.com/fission/fission/issues/690

**Closed** 2018-08-27 06:14 UTC
