### ISSUE TITLE
Logger Warning: Unknown placeholder `${kubernetes_labels_functionUid}` found

### ISSUE THREAD

**Issue by life1347** [fission/fission#625] opened 2018-04-16 07:46 UTC
```
2018-04-16 07:40:23 +0000 [info]: #0 disable filter chain optimization because [Fluent::KubernetesMetadataFilter] uses `#filter_stream` method.
2018-04-16 07:40:23 +0000 [warn]: #0 record_reformer: unknown placeholder `${kubernetes_labels_functionUid}` found
```

**Comment by vishal-biyani** [comment] 2019-02-27 16:52
Closing as a duplicate of #1053

**Closed by vishal-biyani** 2019-02-27 16:52 UTC
