### ISSUE TITLE
Some HTTP Requests Failed During High Pressure Test

### ISSUE THREAD

**Issue by xiekeyang** [fission/fission#695] opened 2018-05-22 09:46 UTC
Hi, I meet a problem on fission pressure request case.

I create a python function with middle cpu and memory load, which use some `numpy` and `panda` methods.

And then, I run http requests with 128 concurrence. After long time running, some failed request happens (about 1%~2%).

I trace the log of `router` and `executor`, as the below:

### executor Log

**After function created, a pod in deployment seems to be cleaned up**:

```
2018/05/21 09:10:39 Creating pool for environment {python-36-lhl2  default /apis/fission.io/v1/namespaces/default/environments/python-36-lhl2 ef22c6c2-5ccb-11e8-9fb4-c6a3351369ea 10062683 0 2018-05-21 07:52:39 +0000 UTC <nil> <nil> map[] map[] [] nil [] }
2018/05/21 09:10:39 fetcher image: fission/fetcher:0.7.2, pull policy: Always
2018/05/21 09:10:39 Cleaning up deployment python-36-lhl1-63a3c180-5a46-11e8-9fb4-c6a3351369ea-t81dlmfu
2018/05/21 09:10:39 [{python-36-lhl2  default /apis/fission.io/v1/namespaces/default/environments/python-36-lhl2 ef22c6c2-5ccb-11e8-9fb4-c6a3351369ea 10062683 0 2018-05-21 07:52:39 +0000 UTC <nil> <nil> map[] map[] [] nil [] }] Deployment created
2018/05/21 09:10:39 Creating pool for environment {python-36-new  default /apis/fission.io/v1/namespaces/default/environments/python-36-new c4c059f6-59b5-11e8-9fb4-c6a3351369ea 8647465 0 2018-05-17 09:36:25 +0000 UTC <nil> <nil> map[] map[] [] nil [] }
2018/05/21 09:10:39 fetcher image: fission/fetcher:0.7.2, pull policy: Always
2018/05/21 09:10:39 Cleaning up deployment python-36-lhl2-ef22c6c2-5ccb-11e8-9fb4-c6a3351369ea-drwxasha

``` 

After long time request started, `No cached function service found` and `executor` try to found available pod:

```
2018/05/21 09:33:54 [json-upload] Checking for cached function service
2018/05/21 09:33:54 [json-upload] No cached function service found, creating one
2018/05/21 09:33:54 [json-upload] getting environment for function
2018/05/21 09:33:54 [json-upload] Checking for cached function service
2018/05/21 09:33:54 Waiting for concurrent request for the same function: &ObjectMeta{Name:json-upload,GenerateName:,Namespace:default,SelfLink:/apis/fission.io/v1/namespaces/default/functions/json-upload,UID:11654455-5cda-11e8-a3dd-6c92bf6f7932,ResourceVersion:10093884,Generation:0,CreationTimestamp:2018-05-21 09:33:49 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,}
2018/05/21 09:33:54 [&ObjectMeta{Name:json-upload,GenerateName:,Namespace:default,SelfLink:/apis/fission.io/v1/namespaces/default/functions/json-upload,UID:11654455-5cda-11e8-a3dd-6c92bf6f7932,ResourceVersion:10093884,Generation:0,CreationTimestamp:2018-05-21 09:33:49 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,}] getting env
2018/05/21 09:33:54 [json-upload] Checking for cached function service
2018/05/21 09:33:54 Waiting for concurrent request for the same function: &ObjectMeta{Name:json-upload,GenerateName:,Namespace:default,SelfLink:/apis/fission.io/v1/namespaces/default/functions/json-upload,UID:11654455-5cda-11e8-a3dd-6c92bf6f7932,ResourceVersion:10093884,Generation:0,CreationTimestamp:2018-05-21 09:33:49 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,}
2018/05/21 09:33:54 [json-upload] getting function service from pool
2018/05/21 09:33:54 [json-upload] Choosing pod from pool
2018/05/21 09:33:54 [json-upload] Checking for cached function service
2018/05/21 09:33:54 Waiting for concurrent request for the same function: &ObjectMeta{Name:json-upload,GenerateName:,Namespace:default,SelfLink:/apis/fission.io/v1/namespaces/default/functions/json-upload,UID:11654455-5cda-11e8-a3dd-6c92bf6f7932,ResourceVersion:10093884,Generation:0,CreationTimestamp:2018-05-21 09:33:49 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,}
2018/05/21 09:33:54 [map[executorInstanceId:mmqarsgg unmanaged:true functionName:json-upload functionUid:11654455-5cda-11e8-a3dd-6c92bf6f7932]] found 3 ready pods of 3 total
```

### Router Log

At this moment(2018/05/21 09:33:54), router log shows that the cleaned pod (`python-36-lhl2-ef22c6c2-5ccb-11e8-9fb4-c6a3351369ea-drwxasha`) is stilled be searched, and return not found, with (`http: proxy error: Resource not found`). It is recorded in ETCD?

```
2018/05/21 09:33:54 http: proxy error: Internal error - deployments.extensions "python-36-lhl2-ef22c6c2-5ccb-11e8-9fb4-c6a3351369ea-drwxasha" not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
2018/05/21 09:33:54 http: proxy error: Resource not found - key '11654455-5cda-11e8-a3dd-6c92bf6f7932_10093884' not found
```

I use the version of 0.7.2, both server and client. What is the root cause?

Thanks so much!

**Comment by soamvasani** [comment] 2018-05-22 17:40
Thanks for doing this testing @xiekeyang !  This is a good test.

At first glance this looks like a cache invalidation bug...  we'll take a deeper look.

**Comment by life1347** [comment] 2018-06-20 16:57
The error message `Resource not found` is expected for executor failed to get the entry for function from function service cache. It was caused by a failure at creating pool for function (due to deployment was deleted).

For the problem that clean deployment is still being searched, so far I cannot find anything suspicious from the source code. Also, the router log 
```
2018/05/21 09:33:54 http: proxy error: Internal error - deployments.extensions "python-36-lhl2-ef22c6c2-5ccb-11e8-9fb4-c6a3351369ea-drwxasha" not found
```
was coming from executor which means that it should also exist in executor log, however, it's not.

Since I cannot reproduce the problem and don't have enough information to debug with, I add some useful log for debugging to executor instead. (PR #752)

@xiekeyang I close this issue for now but feel free to reopen it. And once you can reproduce the problem, it will be super helpful to attach the full log of executor, router, controller and steps for how to reproduce it. And thanks for your report, we will keep an eye on it and fix it once the root cause is found.

**Closed by life1347** 2018-06-20 16:57 UTC
