### ISSUE TITLE
Error getting controller pod for port-forwarding - Fresh Install

### ISSUE THREAD

**Issue by justinhauer** [fission/fission#774] opened 2018-07-03 14:24 UTC
## Error
I get this error after a fresh install of fission on AKS. ➜ ~ fission env create --name nodejs --image fission/node-env:0.8.0
Error getting controller pod for port-forwarding
## Description
No RBAC enabled between Helm and Tiller for the cluster so I'm not sure what is wrong. 

When you say ["If fission has not been setup (correctly), port forwarding will fail"](https://github.com/fission/fission/issues/567), can you be less vague about what can potentially go wrong if your install steps have been followed to a tee? Is this dependent on specific versions of helm, tiller and Kubernetes? If so can you publish what versions you (as a project) have found this to work successfully on?
```helm version:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}```

**Comment by MarcErdmann** [comment] 2018-10-05 14:50
Same problem here with minikube 0.29. Service:

```NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
controller                              NodePort    10.100.124.150   <none>        80:31313/TCP     1d
executor                                ClusterIP   10.102.184.71    <none>        80/TCP           1d
fission-prometheus-alertmanager         ClusterIP   10.105.41.229    <none>        80/TCP           1d
fission-prometheus-kube-state-metrics   ClusterIP   None             <none>        80/TCP           1d
fission-prometheus-node-exporter        ClusterIP   None             <none>        9100/TCP         1d
fission-prometheus-pushgateway          ClusterIP   10.107.85.79     <none>        9091/TCP         1d
fission-prometheus-server               ClusterIP   10.102.183.160   <none>        80/TCP           1d
influxdb                                ClusterIP   10.100.60.195    <none>        8086/TCP         1d
nats-streaming                          NodePort    10.106.125.8     <none>        4222:31316/TCP   1d
redis                                   ClusterIP   10.99.125.239    <none>        6379/TCP         1d
router                                  NodePort    10.100.11.51     <none>        80:31314/TCP     1d
storagesvc                              ClusterIP   10.103.34.140    <none>        80/TCP           1d```

Deployment:

```NAME                                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
buildermgr                              1         1         1            1           1d
controller                              1         1         1            1           1d
executor                                1         1         1            1           1d
fission-prometheus-alertmanager         1         1         1            1           1d
fission-prometheus-kube-state-metrics   1         1         1            1           1d
fission-prometheus-pushgateway          1         1         1            1           1d
fission-prometheus-server               1         1         1            1           1d
influxdb                                1         1         1            1           1d
kubewatcher                             1         1         1            1           1d
mqtrigger-nats-streaming                1         1         1            1           1d
nats-streaming                          1         1         1            1           1d
router                                  1         1         1            1           1d
storagesvc                              1         1         1            1           1d
timer                                   1         1         1            1           1d```

**Comment by paraspatidar** [comment] 2018-10-10 12:49
This may be very well caused by any of the following 
(1) Certificate issue in kubeconfig which may cause 401 , resulting in error getting controller pod
(2) Token  issue in kubeconfig which may cause 401 , resulting in error getting controller pod
(3) RBAC issue.

for me it was certificate issue first , then enabling insecure-skip-tls-verify: true IN KUBECONFIG  made it worked.

Then later on , then i was playing with Rbac then started getting this issue due to rbac

**Comment by wengangJi** [comment] 2018-10-23 09:56
```
controller                              NodePort    10.100.124.150   <none>        80:31313/TCP     1d
```

**Comment by rakeshpatri** [comment] 2018-12-17 10:10
Any solution to this problem yet?

**Comment by Akuan1994** [comment] 2019-04-05 19:07
hi~ what the solution of this question? "Fatal error: Error getting controller pod for port-forwarding"

**Comment by life1347** [comment] 2019-07-06 20:30
From user [feedback](https://fissionio.slack.com/archives/C3LUX6BBP/p1559908112018800) on slack. You'll need to add cert/token to `~/.kube/config`.
Close it now, feel free to reopen it if needed.

**Closed by life1347** 2019-07-06 20:30 UTC
