### ISSUE TITLE
OOMKilled pod starts dropping request

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1874] opened 2020-12-03 07:55 UTC
If a pod is OOMKilled and restarted, the requests going to that pod typically do not work and start throwing 502. This was observed in a customer's environment with a custom python env which was using Debian image. It is not clear if this is a fetcher or env or executor issue but needs to be investigated and fixed.

**Comment by vishal-biyani** [comment] 2020-12-23 07:12
Hey @therahulbhati Also please take a look at https://github.com/fission/fission/issues/1676

**Comment by therahulbhati** [comment] 2021-01-06 13:41
I found [this project](https://github.com/zapier/preoomkiller-controller), informer watches the memory usage using labels and gracefully evict selected pods if a certain threshold is reached. We can give labels and annotations in env specs.

**Comment by abbaspw21** [comment] 2021-03-16 14:33
HI @vishal-biyani @therahulbhati  ,

We are also facing the same issue on few of our production environments. 
In our case we cqn clearly see in logs that a python3.7 process was terminate by OOM killer and after that our fission function which also runs on python3.7 internally started throwing 502.

Logs :
Mar 08 07:55:47 dc1cef kernel: **memory: usage 131072kB, limit 131072kB, failcnt 2814**
Mar 08 07:55:47 dc1cef kernel: memory+swap: usage 131072kB, limit 131072kB, failcnt 0
Mar 08 07:55:47 dc1cef kernel: kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
Mar 08 07:55:47 dc1cef kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Mar 08 07:55:47 dc1cef kernel: [21587]     0 21587  3722868    31476    1475        0           999 python3.7
Mar 08 07:55:47 dc1cef kernel: **Memory cgroup out of memory: Kill process 1154 (python3.7) score 1981 or sacrifice child**
Mar 08 07:55:47 dc1cef kernel: **Killed process 21587 (python3.7), UID 0, total-vm:14891472kB, anon-rss:119828kB, file-rss:6076kB, shmem-rss:0kB**
Mar 08 07:55:48 dc1cef dockerd-current[1243]: {"level":"error","ts":"2021-03-08T12:55:48.053Z","logger":"triggerset.http_trigger_set.snow-to-platform.roundtripper","caller":"router/functionHandler.go:276","msg":"encountered non-network dial error","error":"EOF"}
Mar 08 07:55:48 dc1cef dockerd-current[1243]: {"level":"error","ts":"2021-03-08T12:55:48.053Z","logger":"triggerset.http_trigger_set.snow-to-platform","caller":"router/functionHandler.go:577","msg":"error sending request to function","error":"EOF","function":{"metadata":{"name":"snow-to-platform","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/snow-to-platform","uid":"6347a5fe-3a1e-4b4d-acd6-cd3faaff6109","resourceVersion":"77143306","generation":1,"creationTimestamp":"2021-03-01T09:28:18Z","annotations":{"fission-name":"snow-to-platform","fission-uid":"default-atomiq-py-ssh-snow-to-platform"}},"spec":{"environment":{"namespace":"fission-function","name":"atomiq-py-ssh"},"package":{"packageref":{"namespace":"default","name":"snow-to-platform","resourceversion":"77143299"}},"secrets":null,"configmaps":[{"namespace":"default","name":"snow-to-platform-configmap"},{"namespace":"default","name":"account-configmap"},{"namespace":"default","name":"snow-to-platform-details"},{"namespace":"default","name":"security-configmap"}],"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"newdeploy","MinScale":1,"MaxScale":1,"TargetCPUPercent":80,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":540,"idletimeout":30,"concurrency":50}},"request_header":{"Accept-Encoding":["gzip"],"Content-Length":["1024"],"Content-Type":["application/json"],"Forwarded":["host=router.fission;"],"User-Agent":["Go-http-client/1.1"],"X-Fission-Full-Url":["/fission-function/snow-to-platform"],"X-Fission-Function-Name":["snow-to-platform"],"X-Fission-Function-Namespace":["default"],"X-Fission-Function-Resourceversion":["77143306"],"X-Fission-Function-Uid":["6347a5fe-3a1e-4b4d-acd6-cd3faaff6109"],"X-Fission-Mqtrigger-Errortopic":[""],"X-Fission-Mqtrigger-Resptopic":[""],"X-Fission-Mqtrigger-Topic":["ext_entrytonifi"],"X-Forwarded-For":["10.244.0.240"],"X-Forwarded-Host":["router.fission"]}}
Mar 08 07:55:48 dc1cef dockerd-current[1243]: {"level":"error","ts":"2021-03-08T12:55:48.058Z","logger":"kafka","caller":"kafka/kafka.go:377","msg":"message received to publish to error topic, but no error topic was set","**message":"request returned failure: 502"**,"trigger":"ext-entrytonifi-snow-to-platform","function_url":"http://router.fission/fission-function/snow-to-platform"}

Is there any WA available for the same? 

Also, we would request you to priorities this thing if possible.

**Comment by vishal-biyani** [comment] 2021-03-22 09:29
Related upstream issue: https://github.com/kubernetes/kubernetes/issues/69676

**Comment by abbaspw21** [comment] 2021-03-31 08:53
Hi @vishal-biyani,

We were working on implementing the suggested WA but there we see below issues that can come with the functions which have there own memory limits(defined using  --maxmemory) : 
- Functions with memory limit lower than that is defined in the environment would never be caught by preoomkiller.
- Functions with memory limit higher than that is defined in the environment would get evicted even when they are not OOM

**Comment by vishal-biyani** [comment] 2021-03-31 10:52
@abbaspw21 In the case of pool manager functions - the memory & CPU assigned at the function level are not used but only the one provided at the Env level is used.

Secondly - the value in annotation `preoomkiller.alpha.k8s.zapier.com/memory-threshold` should be defined as around ~95% of RequestLimit of the pod. That ways the pod does not cross the limit and does not run into the OOMKilled issue.

**Comment by abbaspw21** [comment] 2021-03-31 11:08
@vishal-biyani What if function is new deploy ?

**Comment by sanketsudake** [comment] 2021-12-23 04:53
Reproducing issue with pool manager:

1. Create kind k8s cluster & deploy fission
2. Create env 
```
fission env create --name python --image fission/python-env --mincpu 40 --maxcpu 80   --minmemory 64 --maxmemory 96  --poolsize 1 --version 3
```
3. Create code file
```
$ cat code.py
def main():
    a = []
    while True:
        a.append(' ' * 10**6) #This line will create a OOM in seconds
    return "Done"
```
4. Create fn
```
$ fission fn create --name oom-fn --env python --code code.py 
$ fission env pods --name oom-fn
```
5. On making request we can see function pod is restarted, where as no restart on fetcher pod.

```
fetcher/0.log
python/0.log
python/1.log
```
From a fission perspective, the fn runtime server(python container) would be assumed as specialized.
 But from when the fn runtime server restarted, it's not specialized. When a request is made to the env server we would get an error.
 
 I am planning to try out adding a signal handler in the python server to check we can detect exit signals before OOM.

**Comment by sanketsudake** [comment] 2021-12-24 07:44
#### What happens when container within pods get killed due to OOM ?

- Container is given signal SIGKILL and container is forced to exit.
- Container is stopped immediately and restarted to get rid consumed memory.
- Any process typically can capture signals like SIGTERM or SIGINT, and act on it for cleanup. But in case of SIGKILL we can't really capture it.
- Unless we are using something like proper monitoring or [preoomkiller-controller](https://github.com/zapier/preoomkiller-controller), we cant identify oom situation in advance.
- In case of fission function pod, typically we have two containers function runtime container and fetcher container. Typically function runtime container would hit OOM so it gets restarted.

#### Why we get 502 after function runtime container restart ?

- Before container gets killed due to OOM, it is speciallized container generally, i.e, function is loaded into container and it is serving requests.
- Fission currently doesnt have mechanism to continuously scan and identify if pod got restarted due OOM. 
- Restart window is very small so Fission doesnt even come to know if pod is restarted. 
- Once pod is specialized fission assume pod is able to serve function until gets cleaned up/deleted.
- After container restart, Fission assumes pod is specialized and keeps throwing incoming requests at it. Since function is not loaded after container restart, its generic container and request fails.

#### Possible approaches

   - a. Identify OOM situation in advance and fix it by reducing memory usage of the pod. Or use something like veritical pod autoscaler to increase limits for the particular pod.
   - b. After restart, identify pod restarted due to OOM and get it out of the service.
   - c. After restart, restore state in function pod with specialization and make it ready to serve the function.

a. seems to be more effort on the user side. Where b. would be lot additional scanning on Fission side on continuous basis just to identify OOM scenario. 
Both a. b. try to solve build solution at Fission level where as c. is something could be implemented at environment level.

c. seems easier to get quickly working in the environment.
I did a quick POC for this and after restart of function runtime was respecialized.

https://github.com/fission/environments/pull/213

**Comment by sanketsudake** [comment] 2022-01-18 05:37
I am closing this issue now. As we can't do much on OOM killed pod. 
We can only have a fix at the environment level, so that when the env container restarts function should be reloaded.

Please track the following issue for environment-related fixes.
https://github.com/fission/environments/issues/218

**Closed by sanketsudake** 2022-01-18 05:37 UTC
Labels: area-environment

**Comment by greatewei** [comment] 2023-01-09 06:20
The latest version is to repair for the problem
