### ISSUE TITLE
exec format error on WSL (ubuntu bash in Windows 10) - 32 bit not supported

### ISSUE THREAD

**Issue by whitecolor** [fission/fission#172] opened 2017-04-08 15:58 UTC
Installed `fission` WSL (ubuntu bash in Windows 10)

> -> # file /usr/local/bin/fission
/usr/local/bin/fission: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), statically linked, not stripped

Currently WSL only supports amd64 (native 64bit)

Is there a way to get/build 64-bit compatible version?

**Comment by whitecolor** [comment] 2017-05-26 01:26
Any news on this?

**Comment by soamvasani** [comment] 2017-05-26 04:18
Sorry, don't know how I missed this issue. I'll build an amd64 binary and upload it.

**Comment by soamvasani** [comment] 2017-05-26 05:34
@whitecolor Here's the amd64 binary: http://fission.io/linux/amd64/fission

Would you mind testing it on WSL?

**Comment by estiller** [comment] 2017-06-27 14:04
@soamvasani - Just checked it and I can confirm it works on WSL. Thanks!

**Comment by soamvasani** [comment] 2017-06-28 22:22
@estiller Thanks for testing it, and sorry it was annoying to find! We've now switched to using github releases and I've updated the docs. The linux CLI link from INSTALL.md should now just work, since it's built as amd64; and we're also building a windows .exe in the release now. 

Hope this makes things easier to find for Windows users.  If you find other problems with the docs, I'd love to hear about them (either as new issues or on slack, or email).

Meanwhile, closing this issue since the original error is resolved.

**Closed by soamvasani** 2017-06-28 22:22 UTC
