### ISSUE TITLE
context deadline exceeded when running hello world example on vagrant + virtualbox infra

### ISSUE THREAD

**Issue by jbhfenris** [fission/fission#1464] opened 2019-12-11 14:58 UTC
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2019-12-09T03:58:10Z"
    GitCommit: 9401c1ee8559975ffe97db27d8b3572af9f17eda
    Version: 1.7.1
server:
  fission/core:
    BuildDate: "2019-12-09T03:58:10Z"
    GitCommit: 9401c1ee8559975ffe97db27d8b3572af9f17eda
    Version: 1.7.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Vagrant 2.2.6 + Virtualbox 6.0.14r133895 + Ubuntu 16.04.6
1 master node + 2 worker nodes

**Describe the bug**

I follow tutorial for installation of fission.io without helm, choosing fission-all package.

Installation seems to work fine and I start the hello world example on nodejs environment. The first three lines work fine but when I call fission **_function test --name hello_** I obtain every time the same answer : 

**

> Error: error executing HTTP request: Get http://127.0.0.1:40538/fission-function/hello: context deadline exceeded

**

**To Reproduce**

**Expected result**

**Actual result**

**Screenshots/Dump file**

The logs of the router pod are the following :
<pre>
{"level":"error","ts":1576075124.3736634,"logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:609","msg":"error from GetServiceForFunction","error":"error posting to getting service for function: context deadline exceeded","errorVerbose":"context deadline exceeded\nerror posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction\n\t/go/src/pkg/executor/client/client.go:78\ngithub.com/fission/fission/pkg/router.functionHandler.getServiceEntryFromExecutor\n\t/go/src/pkg/router/functionHandler.go:606\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry.func1\n\t/go/src/pkg/router/functionHandler.go:538\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\t/go/src/pkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry\n\t/go/src/pkg/router/functionHandler.go:530\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\t/go/src/pkg/router/functionHandler.go:194\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:259\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\t/go/src/pkg/router/functionHandler.go:433\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\t/go/src/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","error_message":"error posting to getting service for function: context deadline exceeded","function":"&TypeMeta{Kind:,APIVersion:,}","status_code":500}
{"level":"error","ts":1576075124.373922,"logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:540","msg":"error getting service url from executor","error":"error posting to getting service for function: context deadline exceeded","errorVerbose":"context deadline exceeded\nerror posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction\n\t/go/src/pkg/executor/client/client.go:78\ngithub.com/fission/fission/pkg/router.functionHandler.getServiceEntryFromExecutor\n\t/go/src/pkg/router/functionHandler.go:606\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry.func1\n\t/go/src/pkg/router/functionHandler.go:538\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\t/go/src/pkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry\n\t/go/src/pkg/router/functionHandler.go:530\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\t/go/src/pkg/router/functionHandler.go:194\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:259\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\t/go/src/pkg/router/functionHandler.go:433\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\t/go/src/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","function_name":"hello"}
{"level":"error","ts":1576075124.3740563,"logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:565","msg":"error updating service address entry for function","error":"error posting to getting service for function: context deadline exceeded","errorVerbose":"context deadline exceeded\nerror posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction\n\t/go/src/pkg/executor/client/client.go:78\ngithub.com/fission/fission/pkg/router.functionHandler.getServiceEntryFromExecutor\n\t/go/src/pkg/router/functionHandler.go:606\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry.func1\n\t/go/src/pkg/router/functionHandler.go:538\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\t/go/src/pkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry\n\t/go/src/pkg/router/functionHandler.go:530\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\t/go/src/pkg/router/functionHandler.go:194\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:259\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\t/go/src/pkg/router/functionHandler.go:433\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\t/go/src/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","function_name":"hello","function_namespace":"default"}
{"level":"error","ts":1576075124.3741784,"logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:651","msg":"error sending request to function","error":" - error updating service address entry for function hello_default: error posting to getting service for function: context deadline exceeded","function":"&TypeMeta{Kind:,APIVersion:,}","request_header":{"Accept-Encoding":["gzip"],"Forwarded":["host=127.0.0.1:39382;"],"User-Agent":["Go-http-client/1.1"],"X-Fission-Full-Url":["/fission-function/hello"],"X-Fission-Function-Name":["hello"],"X-Fission-Function-Namespace":["default"],"X-Fission-Function-Resourceversion":["4053"],"X-Fission-Function-Uid":["9d2497b0-064c-40e3-9536-5036450fed37"],"X-Forwarded-For":["127.0.0.1"],"X-Forwarded-Host":["127.0.0.1:39382"]}}
</pre>

<pre>
$ fission support dump
[fission-dump_1576075518.zip](https://github.com/fission/fission/files/3950963/fission-dump_1576075518.zip)
</pre>

Status of pod and svc on fission namespace

$ kubectl get pod,svc -n fission
<pre>
NAME                                                               READY   STATUS             RESTARTS   AGE
pod/buildermgr-c7dc44cf9-bfckl                                     1/1     Running            0          38m
pod/controller-6bdcd6f9cd-xcwxs                                    1/1     Running            0          38m
pod/executor-6c6c45bd88-qv8ll                                      1/1     Running            0          38m
pod/fission-1-7-1-fission-al-1.7.1-036-nlxd8                       0/1     Completed          0          38m
pod/fission-1-7-1-fission-al-1.7.1-329-g62db                       0/1     Completed          0          38m
pod/fission-1-7-1-prometheus-alertmanager-996f9b4d7-lddtz          0/2     Pending            0          38m
pod/fission-1-7-1-prometheus-kube-state-metrics-5987f86d74-n2cgn   1/1     Running            0          38m
pod/fission-1-7-1-prometheus-node-exporter-6sb6j                   1/1     Running            0          38m
pod/fission-1-7-1-prometheus-node-exporter-rqlvm                   1/1     Running            0          38m
pod/fission-1-7-1-prometheus-pushgateway-544d545cf4-g8znj          1/1     Running            0          38m
pod/fission-1-7-1-prometheus-server-7f7cd49c9f-t69vb               0/2     Pending            0          38m
pod/influxdb-65bc879d45-nzjfl                                      1/1     Running            0          38m
pod/kubewatcher-54db94f8bb-zwnxx                                   1/1     Running            1          38m
pod/logger-gqfzf                                                   2/2     Running            0          38m
pod/logger-mbmf8                                                   2/2     Running            0          38m
pod/mqtrigger-nats-streaming-68647f8c88-pswjw                      0/1     CrashLoopBackOff   12         38m
pod/nats-streaming-74584c7d6d-rfx8h                                1/1     Running            0          38m
pod/router-c6d7df54f-d56lf                                         1/1     Running            0          38m
pod/storagesvc-5fcfbf4467-nrlrr                                    0/1     Pending            0          38m
pod/timer-8444dccfc8-l5p9d                                         1/1     Running            0          38m

NAME                                                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/controller                                    ClusterIP      10.96.238.14    <none>        80/TCP         38m
service/executor                                      ClusterIP      10.96.226.208   <none>        80/TCP         38m
service/fission-1-7-1-prometheus-alertmanager         ClusterIP      10.96.127.100   <none>        80/TCP         38m
service/fission-1-7-1-prometheus-kube-state-metrics   ClusterIP      None            <none>        80/TCP         38m
service/fission-1-7-1-prometheus-node-exporter        ClusterIP      None            <none>        9100/TCP       38m
service/fission-1-7-1-prometheus-pushgateway          ClusterIP      10.96.2.253     <none>        9091/TCP       38m
service/fission-1-7-1-prometheus-server               ClusterIP      10.96.12.172    <none>        80/TCP         38m
service/influxdb                                      ClusterIP      10.96.228.189   <none>        8086/TCP       38m
service/nats-streaming                                ClusterIP      10.96.202.189   <none>        4222/TCP       38m
service/router                                        LoadBalancer   10.96.155.10    <pending>     80:30214/TCP   38m
service/storagesvc                                    ClusterIP      10.96.183.208   <none>        80/TCP         38m
</pre>

**Additional context**

**Comment by life1347** [comment] 2019-12-11 16:20
Hi @jbhfenris from the pod status, I suspect the vm doesn't have enough resources to run all necessary Fission components. For example,
```
pod/storagesvc-5fcfbf4467-nrlrr                                    0/1     Pending  
```
Could you try to add more resources to the VM and try it again?
I personally would give 4 cpu and 8 gb memory.

**Comment by jbhfenris** [comment] 2019-12-11 16:50
Here is the errors on the pod relative to storagesvc
<pre>
Events:
  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  <unknown>               default-scheduler  error while running "VolumeBinding" filter plugin for pod "storagesvc-5fcfbf4467-nrlrr": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  7m19s (x113 over 163m)  default-scheduler  error while running "VolumeBinding" filter plugin for pod "storagesvc-5fcfbf4467-nrlrr": pod has unbound immediate PersistentVolumeClaims
</pre>

**Comment by life1347** [comment] 2019-12-11 17:55
I check the dump log. It's weird for the executor doesn't receive any requests from the router.

Could you help to set `DEBUG_ENV` in both `router` and `executor` deployments to `true`, the component will show log detail debug log.
```
        - name: DEBUG_ENV
          value: "true"
```

Reproduce the problem, and share the dump file output by `fission support dump`. Thanks.

**Comment by jbhfenris** [comment] 2019-12-12 09:13
Hi @life1347,
I reproduce the issue with the debug activated on the 2 pods and here is the debug file
[fission-dump_1576141432.zip](https://github.com/fission/fission/files/3954846/fission-dump_1576141432.zip)

**Comment by life1347** [comment] 2019-12-12 09:21
@jbhfenris Would you mind to join the Slack and ping me? So that we can have some discussion about the problem. Thanks.

**Comment by jbhfenris** [comment] 2019-12-12 13:01
<pre>
$ kubectl -n fission get pod -o wide
NAME                                                           READY   STATUS      RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
buildermgr-854d4fcd6b-hmjp6                                    1/1     Running     0          92m   10.244.2.21      kubnode2   <none>           <none>
controller-57ff6b474c-glvr5                                    1/1     Running     0          92m   10.244.2.20      kubnode2   <none>           <none>
executor-d75658778-hwv5x                                       1/1     Running     0          83m   10.244.1.33      kubnode    <none>           <none>
fission-1-7-1-fission-co-1.7.1-363-clpcl                       0/1     Completed   0          92m   10.244.1.30      kubnode    <none>           <none>
fission-1-7-1-fission-co-1.7.1-488-nwpwk                       0/1     Completed   0          92m   10.244.2.23      kubnode2   <none>           <none>
fission-1-7-1-prometheus-alertmanager-996f9b4d7-5fjzh          0/2     Pending     0          92m   <none>           <none>     <none>           <none>
fission-1-7-1-prometheus-kube-state-metrics-5987f86d74-lmcbf   1/1     Running     0          92m   10.244.2.24      kubnode2   <none>           <none>
fission-1-7-1-prometheus-node-exporter-9z2nm                   1/1     Running     0          92m   192.168.56.103   kubnode2   <none>           <none>
fission-1-7-1-prometheus-node-exporter-pwhk9                   1/1     Running     0          92m   192.168.56.102   kubnode    <none>           <none>
fission-1-7-1-prometheus-pushgateway-544d545cf4-f82mx          1/1     Running     0          92m   10.244.2.22      kubnode2   <none>           <none>
fission-1-7-1-prometheus-server-7f7cd49c9f-4pvpq               0/2     Pending     0          92m   <none>           <none>     <none>           <none>
kubewatcher-77b94ddb5c-bcckj                                   1/1     Running     0          92m   10.244.1.27      kubnode    <none>           <none>
router-644878c58b-z8j57                                        1/1     Running     0          86m   10.244.1.32      kubnode    <none>           <none>
storagesvc-68d87f54dc-mf6tr                                    0/1     Pending     0          92m   <none>           <none>     <none>           <none>
timer-f4f6677bc-shkb6                                          1/1     Running     0          92m   10.244.1.28      kubnode    <none>           <none>
</pre>

For the router pod, once I'm connected on it, I'm not able to download the curl apk but I may ping the executor-ip

<pre>
# wget -S http://10.244.1.33:8888/healthz
Connecting to 10.244.1.33:8888 (10.244.1.33:8888)
  HTTP/1.1 200 OK
  Date: Thu, 12 Dec 2019 12:49:48 GMT
  Content-Length: 0
  Connection: close
</pre>

<pre>
# nslookup executor.fission
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'executor.fission': Try again
</pre>
the kube-dns seems to cause problem and are not reachable for the pod

The /etc/resolv.conf on the router pod contains :
<pre>
 # more resolv.conf
nameserver 10.96.0.10
search fission.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
</pre>

From the master, I'm able to query the kube-dns service running on 10.96.0.10
<pre>
dig google.com @10.96.0.10

; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.com @10.96.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44553
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		30	IN	A	216.58.204.110

;; Query time: 1 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Thu Dec 12 13:00:14 UTC 2019
;; MSG SIZE  rcvd: 65
</pre>

**Comment by life1347** [comment] 2019-12-12 14:37
Ok, so the problem is due to the pod cannot get dns result from the dns service. You may want to check the network connectivity between master node and worker node. 

These links should be helpful for DNS problem:
1. https://github.com/kubernetes/kubeadm/issues/1056
2. https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Since this issue is out of scope that Fission can control, close it for now. Feel free to reopen it.

**Closed by life1347** 2019-12-12 14:37 UTC

**Comment by jbhfenris** [comment] 2019-12-12 15:42
Thanks for the support, the issue was effectively dues to Flannel configuration where a specific configuration should be applied when used with Vagrant.
