### ISSUE TITLE
Segragation of WaitTime and RunTime for implementing fntimeout

### ISSUE THREAD

**Issue by msshroff** [fission/fission#1693] opened 2020-08-31 05:33 UTC
Currently we have "TimeOut" for any function call based on `--fntimeout`

But it does not consider separately: 

1. The time function call is waiting for the getting the POD, specializing it
2. Actual Runtime of the function call 

We need ability to have separate timeouts for "WaitTime" and "RunTime"

**Comment by vishal-biyani** [comment] 2020-09-17 16:10
Hi @msshroff I confirmed from code and we actually use the user passed `fntimeout` for the request we make to the executor (Reference: https://github.com/fission/fission/blob/master/pkg/router/functionHandler.go#L385 ). Any waiting time that happens is before this if the pod was busy. Also with the new concurrency feature - this wait time does not exist and if a request can be served because the function has reached concurrency limit then a [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) is returned to the user. I would recommend trying 1.11.0 for this use case and let us know if this is still an issue!

**Comment by vishal-biyani** [comment] 2020-11-09 08:13
Hi @msshroff I will close this issue for now, but please re-open if needed

**Closed by vishal-biyani** 2020-11-09 08:13 UTC
Labels: area-routing, question
