### ISSUE TITLE
Fission 1.14.1 Eerror getting Fission API version: unexpectred end of JSON input.

### ISSUE THREAD

**Issue by atsai1220** [fission/fission#2253] opened 2021-11-05 00:17 UTC
**Fission/Kubernetes version**

<pre>
❯ kubectl port-forward svc/router -n fission 8000:80 &
❯ fission version
Handling connection for 8000
Warning: Error getting Fission API version: unexpected end of JSON input
client:
  fission/core:
    BuildDate: "2021-08-03T11:34:27Z"
    GitCommit: 9b5eb069d69d47d22ecc0270bf8619857ea3f19f
    Version: 1.14.1
server:
  fission/core: {}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Describe the bug**

Fresh install of Fission and none of the commands work. Changing `kubeconfig` to an existing Fission installation results in the same output.
```
❯ fission fn list
Handling connection for 8000

Options:
  --fnNamespace='default' (--fns)  Namespace for function object

Global Options:
  --server=''         Server URL
  --verbosity=1 (-v)  CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
  --kube-context=''   Kubernetes context to be used for the execution of Fission commands

Usage:
  fission function list [options]

Error: error listing functions: Resource not found - 404 page not found
```

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>
[fission-dump_1636069392.zip](https://github.com/fission/fission/files/7479589/fission-dump_1636069392.zip)

**Comment by atsai1220** [comment] 2021-11-05 00:20
This was my bad.
My fix was to make sure not to set additional environment variables and only set `FISSION_ROUTER` without `http://`

```
❯ unset FISSION_ROUTER
❯ unset FISSION_URL

❯ export FISSION_ROUTER="127.0.0.1:8000"
```

**Comment by atsai1220** [comment] 2021-11-05 00:55
What's even more weird is if I `unset FISSION_URL` in one session and run `fission version --verbosity=2` I would receive loads of `Handling connection for 65385` but the command would not return.

However, if I open another Terminal and run then the result is immediate.
```
❯ export FISSION_URL="http://127.0.0.1:65385"
❯ fission version --verbosity=2
client:
  fission/core:
    BuildDate: "2021-08-03T11:34:27Z"
    GitCommit: 9b5eb069d69d47d22ecc0270bf8619857ea3f19f
    Version: 1.14.1
server:
  fission/core:
    BuildDate: "2021-08-03T09:53:20Z"
    GitCommit: 9b5eb069d69d47d22ecc0270bf8619857ea3f19f
    Version: 1.14.1
```

It seems like I am able to port-forward manually but unable the FIssion CLI is unable to port-forward for me in the same command and I am unable to port-forward with my own `kubectl port-forward svc/router` command because it would return 404 for some reason.

**Comment by atsai1220** [comment] 2021-11-05 01:13
Running a freshly downloaded 1.14.1 CLI on Ubuntu resolves this issue completely. Running on MacOS 11.6 is giving me issues. May be something on my network.

**Comment by sanketsudake** [comment] 2021-11-08 06:13
Hey, @atsai1220 I think 404 for `http://127.0.0.1:8888/v2` would be because of the path not found.

Apart from that, the errors you have mentioned above seems to be set up specific. If you are still able to reproduce any of the issues or facing consistently, let me know.

**Comment by sanketsudake** [comment] 2021-11-16 06:57
Hey, @atsai1220 Closing this issue doesn't seem to be caused by Fission at the point. Feel free to reopen with more details if you are able to reproduce it.

**Closed by sanketsudake** 2021-11-16 06:57 UTC
Labels: area-function, area-fission-cli
